# fly.toml app configuration file generated for dheris-chatwoot on 2023-09-03T12:26:40+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dheris-chatwoot"
primary_region = "sin"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
