# fly.toml app configuration file generated for dheris-chatwoot on 2023-09-04T09:16:42+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dheris-chatwoot"
primary_region = "sin"
console_command = "/rails/bin/rails console"

[build]

[env]
  ENABLE_ACCOUNT_SIGNUP = "true"
  RAILS_ENV = "production"

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
